obj-$(CONFIG_GPIO_QPNP_PIN)	+= qpnp-pin.o
obj-$(CONFIG_LEDS_QPNP)			+= leds-qpnp.o
obj-$(CONFIG_LEDS_QPNP_WLED)		+= leds-qpnp-wled.o
obj-$(CONFIG_PWM_QPNP)		+= pwm-qpnp.o
obj-$(CONFIG_QPNP_COINCELL) += qpnp-coincell.o
obj-$(CONFIG_RTC_DRV_QPNP)	+= qpnp-rtc.o